name: nanoplan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  get: 4.6.6
  nanoid: ^1.0.0
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  pocketbase: ^0.18.1
  bootstrap_icons: ^1.11.3
  simple_gradient_text: 1.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/videos/
  uses-material-design: true

